name: Build Python Wheels

on:
  workflow_call:

jobs:
  sdist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install build
        run: python -m pip install --upgrade pip build

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload sdist
        uses: actions/upload-artifact@v7
        with:
          name: wheels-sdist
          path: dist/*

  wheel:
    needs: ['sdist']
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-2022
            arch: x86
          - runner: windows-2022
            arch: AMD64
          - runner: windows-11-arm
            arch: ARM64
    steps:
      - name: Download sdist artifact
        uses: actions/download-artifact@v8
        with:
          name: wheels-sdist
          path: dist

      - name: Extract sdist
        shell: bash
        run: |
          mkdir -p package
          mv dist/*.tar.gz winflexbison.tar.gz

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.2.0

      - uses: pypa/cibuildwheel@v3.4.1
        with:
          package-dir: winflexbison.tar.gz
        env:
          CIBW_BUILD: 'cp310-*'
          CIBW_ARCHS: '${{ matrix.platform.arch }}'

      - run: ls -ahl wheelhouse
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ runner.os }}-${{ matrix.platform.arch }}
          path: wheelhouse/*

  merge-wheel-artifact:
    runs-on: ubuntu-slim
    needs: ['sdist', 'wheel']
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v7
        with:
          name: wheel
          pattern: wheels-*
